apiVersion: apps/v1
kind: Deployment
metadata:
  name: mayank-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mayank
  template:
    metadata:
      labels:
        app: mayank
    spec:
      containers:
      - name: mayank
        image: 079819354494.dkr.ecr.us-west-2.amazonaws.com/mayank:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mayank
    k8s-app: mayank
  name: mayank
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: mayank
