apiVersion: apps/v1
kind: Deployment
metadata:
  name: jagpsi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jagpsi
  template:
    metadata:
      labels:
        app: jagpsi
    spec:
      containers:
      - name: jagpsi
        image: 139713842946.dkr.ecr.us-west-2.amazonaws.com/jagpsi
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jagpsi
    k8s-app: jagpsi
  name: jagpsi
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: jagpsi
